name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "445b13131546631bbc16248c1a46443421334511526b07f459af81339627d8ce"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
