name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4ae67ec7e391bf9af2041761cd9bb10003f3f0143b4c4282a9f1b73d5a29d2e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1", "1.19"]
