name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e63929a9c35a0c398e4daadb3cd56b726fd80c5b26d14a9590de068d0df36d3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
