name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c2b2efc702640774aba694efda4c1ae90cc0f03df9a7026c70422ab1c684c60"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
