name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59622c7d0f8052befdcadc99fba4306de4db93e3aceea587d32f3fd1cff4221c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
