name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6443cb678df98a758c25109d19b15c758df3bf0bfbbb4c0e887327430c20770"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
