name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b1815697d8b7716b3709470ed71a28984fcc8425ba699ff62cd9ec86d753ea5"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
