name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a946ade46c737cf0bb55d149abaa5f10eb016ed0b5360d028ef7f6f4d311757"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
