name = "Winter Wonderland Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8e2cfaff3bc425e012c3d1d25eb2846d7a24b7415b917510553a7012ed1f53c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
